# Ejercicio 3. Iteración con loops y analisis de sentimientos

#### Alumna: Daniela Lizeth Molina Barrera

Supongamos que realizamos una encuesta para evaluar la calidad de un servicio. Para ello, realizamos un formulario en donde le pedimos a los clientes que comenten sobre el servicio que proveemos.

En este problema, analizaremos estos comentarios ficticios y averiguaremos si el sentimiento general de los usuarios de Zophia es de satisfaccion o no. Esta es una versión simplificada de un importante problema del mundo real llamado análisis de sentimientos.

Antes de empezar, necesitamos una lista de comentarios para analizar. Estamos eligiendo un pequeño número de comentarios aquí, pero el mismo análisis también se puede hacer para miles, o incluso millones de comentarios.

En la celda de abajo tenemos algunos de los comentarios de los usuarios, ya insertados en una lista:

In [1]:
comentarios = [
    "Wow, ¡qué gran servicio!",
    "Aprendí mucho con ustedes",
    "Estoy muy emocionada por aprender más de análisis de datos con Zophia",
    "Curso de calidad",
    "Un curso del montón",
    "Aprendí muchísimo",
    "Está bien pero tienen áreas de oportunidad",
    "Bueno. Pero podrían mejorar",
    "Me siento estafado",
    "Zophia tiene tutoriales geniales de análisis de datos",
    "Definitivamente, volveré a tomar un curso con ustedes",
    "Malo",
    "Cumplió con mis expectativas",
    "Bien explicado, pero le falta",
    "Bueno"
              ]

In [2]:
num_coment = len(comentarios)
num_coment

15

In [3]:
# crear un diccionario de las palabras que considero "buenos comentarios"
comentarios_buenos = ['Wow', 'gran', 'mucho', 'emocionada', 'calidad', 'muchísimo', 'geniales', 'volveré', 'Cumplió']
comentarios_buenos

['Wow',
 'gran',
 'mucho',
 'emocionada',
 'calidad',
 'muchísimo',
 'geniales',
 'volveré',
 'Cumplió']

In [4]:
# crear un diccionario de las palabras que considero "comentarios neutrales"
comentarios_neutrales = ['Está bien', 'Bueno', 'Bien']
comentarios_neutrales

['Está bien', 'Bueno', 'Bien']

In [5]:
# crear un diccionario de las palabras que considero "malos comentarios"
comentarios_malos = ['montón', 'estafado', 'Malo']
comentarios_malos

['montón', 'estafado', 'Malo']

1. Calcula la proporción de comentarios neutrales

In [6]:
# indicamos una variable igual a cero
num_comentarios_neutrales = 0

In [7]:
# realizamos un loop anidado
for comentario in comentarios:
    for neutral in comentarios_neutrales:
        if neutral in comentario:
            num_comentarios_neutrales += 1
            break

num_comentarios_neutrales

4

In [9]:
# calculamos la proporción de comentarios neutrales
proportion_comment_neutral = num_comentarios_neutrales/ 15* 100

print("La proporción de comentarios neutrales es", proportion_comment_neutral)

La proporción de comentarios neutrales es 26.666666666666668


2. Toma 20 opiniones de algun negocio local y realiza el analisis de sentimientos que nosotros hicimos con los comentarios ficticios. Evalua si los comentarios son positivos, negativos o neutrales y asignales un porcentaje correspondiente. Con base en los resultados, emite recomendaciones al negocio.

In [10]:
reseñas = [
    'Le falta fuerza',
    'Excelente producto, cumplé las expectativas',
    'Es una maravilla',
    'Recomendable 100%',
    'No era lo que esperaba',
    'Esperaba que fuera mas silenciosa y rapida',
    'La licuadora perfecta para hacer batidos',
    'Producto basura',
    'Increible licuadora',
    'Todo está bien',
    'Quedé muy agusto con su desempeño',
    'Se raya facilmente',
    'No funciona bien',
    'Increible licuadora',
    'No sirve para hacer batidos, podria mejorarse',
    'Primero me encanto, ahora la odio',
    'Se quiebra con facilidad',
    'Su funcionamiento no es el adecuado',
    'Buen tamaño, facil de lavar y muele perfecto',
    'Cumplé con lo esperado'
]

reseñas

['Le falta fuerza',
 'Excelente producto, cumplé las expectativas',
 'Es una maravilla',
 'Recomendable 100%',
 'No era lo que esperaba',
 'Esperaba que fuera mas silenciosa y rapida',
 'La licuadora perfecta para hacer batidos',
 'Producto basura',
 'Increible licuadora',
 'Todo está bien',
 'Quedé muy agusto con su desempeño',
 'Se raya facilmente',
 'No funciona bien',
 'Increible licuadora',
 'No sirve para hacer batidos, podria mejorarse',
 'Primero me encanto, ahora la odio',
 'Se quiebra con facilidad',
 'Su funcionamiento no es el adecuado',
 'Buen tamaño, facil de lavar y muele perfecto',
 'Cumplé con lo esperado']

In [11]:
# verificar el numero de comentarios
numero_comentarios = len(reseñas)
numero_comentarios

20

In [12]:
# comentarios positivos
comentarios_positivos = ['Excelente','maravilla','perfecta','Increible','agusto','buen','cumplé']
comentarios_positivos

['Excelente', 'maravilla', 'perfecta', 'Increible', 'agusto', 'buen', 'cumplé']

In [13]:
# comentarios neutrales
comentarios_neutrales = ['falta','esperaba','está bien','mejorarse','esperado','falta','esperado']
comentarios_neutrales

['falta',
 'esperaba',
 'está bien',
 'mejorarse',
 'esperado',
 'falta',
 'esperado']

In [14]:
# comentarios negativos
comentarios_negativos = ['adecuado','quiebra','odio','raya','No','basura']
comentarios_negativos

['adecuado', 'quiebra', 'odio', 'raya', 'No', 'basura']

* Calculamos la cantidad y proporción de numeros positivos

In [15]:
# indicamos una variable igual a cero
numero_comentarios_positivos = 0
numero_comentarios_neutrales = 0
numero_comentarios_negativos = 0

In [16]:
# realizamos el loop positivo
for reseña in reseñas:
    for positivo in comentarios_positivos:
        if positivo in reseña:
            numero_comentarios_positivos += 1
            break

numero_comentarios_positivos

6

In [17]:
# realizamos el loop neutrales
for reseña in reseñas:
    for neutral in comentarios_neutrales:
        if neutral in reseña:
            numero_comentarios_neutrales += 1
            break

numero_comentarios_neutrales

5

In [18]:
# realizamos el loop negativos
for reseña in reseñas:
    for negativo in comentarios_negativos:
        if negativo in reseña:
            numero_comentarios_negativos += 1
            break

numero_comentarios_negativos

8

In [19]:
# proporción de comentarios positivos
proporcion_positivos = numero_comentarios_positivos/ 20 *100

enunciado_proporcion_positivos = print("La proporción de comentarios positivos es de ", proporcion_positivos, "%")

La proporción de comentarios positivos es de  30.0 %


In [20]:
# proporción de comentarios neutrales
proporcion_neutrales = numero_comentarios_neutrales/ 20 *100

enunciado_proporcion_neutrales = print("La proporción de comentarios neutrales es de ", proporcion_neutrales, "%")

La proporción de comentarios neutrales es de  25.0 %


In [21]:
# proporción de comentarios positivos
proporcion_negativos = numero_comentarios_negativos/ 20 *100

enunciado_proporcion_negativos = print("La proporción de comentarios negativos es de ", proporcion_negativos, "%")

La proporción de comentarios negativos es de  40.0 %


* Realiza recomendaciones de acuerdo a la proporción de comentarios positivos, negativos y neutrales

<b> Recomendaciones </b> :

Se analizaron 20 comentarios de los cuales se tuvieron los siguientes hallazgos:
 * La proporción de comentarios positivos es de  30.0 %
 * La proporción de comentarios neutrales es de  25.0 %
 * La proporción de comentarios negativos es de  40.0 %
 
 Donde los comentarios negativos de parte de los clientes predominan, donde la principal queja es la facilidad con la que se rayan o quibran los vasos de la licuadora, por lo tanto, se recomienda mejorar la calidad de materiales con los que se producen las licuadoras asi como especificar los productos que puede moler la licuadora.

3. En este ejemplo, nosotros utilizamos palabras positivas o negativas para evaluar la calidad de un servicio. ¿Cómo podríamos evaluar la intención de los comentarios? Por ejemplo, que pasa si alguien escribe: "aprendí un montón". ¿Cómo podríamos diferenciar un comentario positivo de uno negativo? Tip: puedes revisar este paper https://icwsm.org/papers/3--Godbole-Srinivasaiah-Skiena.pdf y otros similares. 

<b> Respuesta: </b>

Se analizan las palabras clave dentro de las reseñas y se clasifican de acuerdo a nuestro criterio en positivas, negativas y neutrales. Aunque tambien ya existen paqueterias creadas que te ayudan a realizar el sentimental analysis. O incorporando algorimos asociados con la polaridad de las palabras que usamos como referencia y de esta forma asignando scores a cada palabra.

4. ¿Cómo podríamos realizar este ejercicio a gran escala (con miles o millones de entradas)?

<b> Respuesta: </b>

Muchas veces se puede realizar ejercicios a gran escala con ayuda de paqueterias creadas para ese tipo de ejercicios, que se hacen con ayuda de API's.

5. Reescribe los While loops utilizados como ejemplo en este Notebook de manera que se conviertan en un código más limpio.